// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaAmRIiix_QkWAK9jbZqj94ZRm3uSV6dU',
    appId: '1:905048305653:web:f7fe583c370fc502343abc',
    messagingSenderId: '905048305653',
    projectId: 'my-to-do-app-yehya403',
    authDomain: 'my-to-do-app-yehya403.firebaseapp.com',
    storageBucket: 'my-to-do-app-yehya403.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8Y_wZ8vL1OqcbbZ86FucSbfy2EnycZgM',
    appId: '1:905048305653:android:0edaf352fb48908b343abc',
    messagingSenderId: '905048305653',
    projectId: 'my-to-do-app-yehya403',
    storageBucket: 'my-to-do-app-yehya403.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIB2Hbc9eiNyMbujymhf28jNLBi9V0Lew',
    appId: '1:905048305653:ios:fe99b4a99e1dcd05343abc',
    messagingSenderId: '905048305653',
    projectId: 'my-to-do-app-yehya403',
    storageBucket: 'my-to-do-app-yehya403.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIB2Hbc9eiNyMbujymhf28jNLBi9V0Lew',
    appId: '1:905048305653:ios:7c6d9461594713d9343abc',
    messagingSenderId: '905048305653',
    projectId: 'my-to-do-app-yehya403',
    storageBucket: 'my-to-do-app-yehya403.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
